require: rubocop-rspec

RSpec/EmptyExampleGroup:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*.rb"

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 15
  CountComments: false
  Exclude:
    - "db/migrate/*.rb"

Metrics/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "lib/tasks/**"
    - "spec/factories/*"
    - "spec/swagger_helper.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/rails_helper.rb'
    - 'spec/response_helper.rb'
    - 'spec/controllers/concerns/respondable_spec.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'config/**/*'
    - 'ng/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'spec/**/*'
    - 'app/jobs/application_job.rb'
